version: '3.1'

networks:
  mariadb:
    driver: bridge

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9901
    ports:
      - 3306:3306
    networks:
      - mariadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - mariadb